name: kp-crm-sms-lambda
on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'gh-action'
      - 'devops'

env:
  DEV_SAM_TEMPLATE: template.yaml
  DEV_STACK_NAME: dev-kp-crm-sms
  DEV_PIPELINE_EXECUTION_ROLE: arn:aws:iam::306364069601:role/deploy-sms
  DEV_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::306364069601:role/CloudformationAdmin
  DEV_ARTIFACTS_BUCKET: aws-sam-kpc-custom-sms-activity-api
  DEV_REGION: ap-southeast-1

  PROD_SAM_TEMPLATE: template-prod.yaml
  PROD_STACK_NAME: prod-kp-crm-sms
  PROD_PIPELINE_EXECUTION_ROLE: arn:aws:iam::173134839626:role/deploy-sms
  PROD_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::173134839626:role/CloudformationAdmin
  PROD_ARTIFACTS_BUCKET: prod-aws-sam-kpc-custom-sms-activity-api
  PROD_REGION: ap-southeast-1

  # If there are functions with "Image" PackageType in your template,
  # uncomment the line below and add "--image-repository ${PROD_IMAGE_REPOSITORY}" to
  # prod "sam package" and "sam deploy" commands.
  # PROD_IMAGE_REPOSITORY = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'

permissions:
  id-token: write
  contents: read
jobs:
  dev-build-and-deploy-kp-crm-sms:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/gh-action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template ${DEV_SAM_TEMPLATE} --use-container
      - name: Assume the DEV pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.DEV_REGION }}
          role-to-assume: ${{ env.DEV_PIPELINE_EXECUTION_ROLE }}
          role-session-name: deploy-sms
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to feature stack in the DEV account
        shell: bash
        run: |
          sam deploy --stack-name $DEV_STACK_NAME \
            --capabilities CAPABILITY_IAM \
            --region ${DEV_REGION} \
            --s3-bucket ${DEV_ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --role-arn ${DEV_CLOUDFORMATION_EXECUTION_ROLE} \
            --parameter-overrides "KPCFunctionName=${DEV_STACK_NAME} Env=dev Host=dev-sms-api.crm.theable.dev Certificate=arn:aws:acm:ap-southeast-1:306364069601:certificate/0908e248-26f3-4352-89e5-67083817b9fb"

  prod-build-and-deploy-kp-crm-sms:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/devops'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam build --template ${PROD_SAM_TEMPLATE} --use-container
      - name: Assume the PROD pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.PROD_REGION }}
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: deploy-sms
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to feature stack in the PROD account
        shell: bash
        run: |
          sam deploy --stack-name $PROD_STACK_NAME \
            --capabilities CAPABILITY_IAM \
            --region ${PROD_REGION} \
            --s3-bucket ${PROD_ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --role-arn ${PROD_CLOUDFORMATION_EXECUTION_ROLE} \
            --parameter-overrides "KPCFunctionName=${PROD_STACK_NAME} Env=prod Host=sms-api.crm.theable.dev Certificate=arn:aws:acm:ap-southeast-1:173134839626:certificate/d6f5c3b6-113a-4920-8406-77c8e3dd7c9d"